# Generated by Django 4.0.3 on 2022-03-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
